# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan Ott Blog
email: jordanott365@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "I have no special talent. I am only passionately curious." - Albert Einstein
baseurl: "" 
url: "http://jordanott.github.io" 

github_username:  jordanott

# Build settings
markdown: kramdown
